
export const metadata = {
  title: 'Contact Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>This is contact page layout</h1>
        {children}</body>
    </html>
  )
}
